// ╔══════════════════════════════════════════════════════════════════════╗
// ║  Re-export wrapper — web app                                       ║
// ║  All types now come from @punto-park-u/shared-types                 ║
// ╚══════════════════════════════════════════════════════════════════════╝

/**
 * All types re-exported from the shared-types package.
 * This file exists as a re-export wrapper so existing imports
 * using the @/types alias continue to work without changes.
 */
export type {
  ApiResponse,
  ApiError,
  AuthResponse,
  AdminStats,
  ActivityLog,
  Alert,
  HourlyOccupancy,
  ParkedVehicle,
  ReportData,
  RetryConfig,
  VehicleType,
  UserRole,
  User,
  UserStats,
  PaginatedResponse,
  UpdateRolePayload,
  Vehicle,
  PriceSet,
  PricingConfig,
  TimeRange,
  Schedule,
  ParkingSpot,
  ParkingStats,
  ParkingEntry,
  ReportFilters,
  ReportSummary,
  ReportBreakdown,
  ReportPaymentKPI,
  ReportKPI,
  ReportRow,
  ReportMeta,
  ReportContent,
  DailyIncome,
  OccupancyByType,
  PaymentMethodStat,
  Reservation,
  Ticket,
  QRValidationResult,
  Payment,
  NotificationSettings,
  LoginCredentials,
  RegisterData,
  TwoFactorStatus,
  TwoFactorSetupData,
  TwoFactorVerifySetupResponse,
  TwoFactorVerifyResponse,
  TwoFactorBackupCodesResponse,
  LoginResponse2FA,
  SessionData,
  SessionStats,
  WsSpotUpdate,
  WsAlertEvent,
  WsActivityEvent,
  AppNotification,
  NotificationsResponse,
  StorageAdapter,
  ApiConfig,
  AppError,
} from '@punto-park-u/shared-types'
